name: Python CI  # Name of the workflow

on: [push, pull_request]  # Run on push or pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use Python 3.10

    - name: Install dependencies (if needed)
      run: |
        python -m pip install --upgrade pip
        test -f requirements.txt && pip install -r requirements.txt || echo "No requirements.txt found, skipping..."

    - name: Run tests
      run: python -m unittest discover  # Run all unit tests
