name: Python CI  # Name of the workflow

on: [push, pull_request]  # Run on push or pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use Python 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies

    - name: Run tests
      run: python -m unittest discover  # Run all unit tests
